### ISSUE TITLE
Тестирование

### ISSUE THREAD

**Issue by opomuc** [DidenkoAndre/gosbookbot#7]
Запилить вменяемый аппарат тестирования бота.

**Comment by DidenkoAndre** [comment]
уже есть же... тестовые субскуперы.

**Comment by opomuc** [comment]
@DidenkoAndre это ты ваще жесть какую-то сделал, честное слово... Надо в нормальный вид привести. И сделать юнит-тесты, наверное...

**Comment by DidenkoAndre** [comment]
та в смысле жесть, это ты сейчас какие-то тарантулы и ненужные кеширования, поиски, докеры хочешь привлечь -- вот это жесть)

и вообще телеграм боты умирают

**Comment by opomuc** [comment]
gently closing, spring cleaning
